export const groceryListMock = [
  {
    id: 182983091390283091,
    title: "mercado 1",
    value: 520.85,
    data: "15/11/2025",
    itens: 52,
    content: [
      {
        id: 1,
        title: "sabao",
        category: "higiene",
        price: 13.75,
        amount: 5,
        mark: "palmoliva",
      },
      {
        id: 2,
        title: "shampo",
        category: "higiene",
        price: 18.0,
        amount: 1,
        mark: "Hedenshozen",
      },
      {
        id: 3,
        title: "manteiga",
        category: "comida",
        price: 14.0,
        amount: 2,
        mark: "delicia",
      },
      {
        id: 4,
        title: "Pneu",
        category: "higiene",
        price: 320.0,
        amount: 1,
        mark: "Pirelli",
      },
      {
        id: 5,
        title: "papel higienico",
        category: "higiene",
        price: 32.0,
        amount: 1,
        mark: "Urso",
      },
      {
        id: 6,
        title: "pasta de dente",
        category: "higiene",
        price: 9.82,
        amount: 1,
        mark: "sorriso",
      },
      {
        id: 7,
        title: "escova de dente",
        category: "higiene",
        price: 19.82,
        amount: 1,
        mark: "sorriso",
      },
      {
        id: 8,
        title: "Guardanapo",
        category: "higiene",
        price: 19.82,
        amount: 1,
        mark: "sorriso",
      },
    ],
  },
  {
    id: 102343982743389,
    title: "mercado 2",
    data: "25/11/2025",
    value: 412.45,
    itens: 32,
    content: [
      {
        id: 1,
        title: "sabao",
        category: "higiene",
        price: 2.75,
        amount: 5,
        mark: "palmoliva",
      },
    ],
  },
];
